# ----------------------NUMPY  EXERCISES--------------------

# In your numpy-pandas-visualization-exercises repo, create a file named numpy_exercises.py for this exercise.

# Use the following code for the questions below:



In [19]:
import numpy as np

import math 


In [7]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [8]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

# 1). How many negative numbers are there?


Answer: 4


In [23]:
negative_numbers = a[ a < 0]

negative_numbers


array([-2, -1, -6, -7])

In [24]:
len(negative_numbers)

4

# 2). How many positive numbers are there?


Answer: 5


In [27]:
positive_numbers = a [a > 0]
positive_numbers

array([ 4, 10, 12, 23,  3])

In [29]:
len(positive_numbers)

5

# 3). How many even positive numbers are there?


 Answer: array([ 4, 10, 12])


In [33]:
even_num = a [a % 2 == 0]

positive_even_num = (even_num [even_num > 0])

positive_even_num

array([ 4, 10, 12])

# 4). If you were to add 3 to each data point, how many positive numbers would there be?

Answer: 10


In [58]:
original = a 

plus_three = original + 3

plus_three_positive  = plus_three[plus_three > 0]



In [59]:
len(plus_three_positive)

10

# 5). If you squared each number, what would the new mean and standard deviation be?
 Asnswer: Squared average = 74.0
 
 
 Answer Standard Deviation = 144.0243035046516


In [72]:
or_num = a 

squared = or_num * a

mean_squared_num = np.average(squared)

mean_squared_num

standard_deviation = np.std(squared)

standard_deviation



144.0243035046516


# 6). A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

# 7). Calculate the z-score for each data point. Recall that the z-score is given by:

# Z = ((x − μ) / σ)


# 8). Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

# Awesome Bonus For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to
# your laptop. Next, go to https://github.com/new to make a new repo. Name it numpy-100, and follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.

In [2]:
a = a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [3]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])